server:
  port: 8085
  servlet:
    context-path: /oid-registry




spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         show_sql: false
         format_sql: false
         ddl-auto: create-drop
         dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
